export const calculatorButtons = [
  { name: 'AC', className: 'calculator__button span ac' },
  { name: 'DEL', className: 'calculator__button' },
  { name: '/', className: 'calculator__button', symbol: '÷' },
  { name: '1', className: 'calculator__button' },
  { name: '2', className: 'calculator__button' },
  { name: '3', className: 'calculator__button' },
  { name: '*', className: 'calculator__button', symbol: '×' },
  { name: '4', className: 'calculator__button' },
  { name: '5', className: 'calculator__button' },
  { name: '6', className: 'calculator__button' },
  { name: '+', className: 'calculator__button' },
  { name: '7', className: 'calculator__button' },
  { name: '8', className: 'calculator__button' },
  { name: '9', className: 'calculator__button' },
  { name: '-', className: 'calculator__button', symbol: '−' },
  { name: '.', className: 'calculator__button' },
  { name: '0', className: 'calculator__button' },
  { name: '=', className: 'calculator__button span', symbol: '=' },
];
